// AUTO-GENERATED by filerouter-cli - DO NOT EDIT
// Generated at: 2026-03-16T20:34:58.888Z

import { createParseRoute, registerCommands } from 'filerouter-cli';
import type { RouteTable, EmptyParams } from 'filerouter-cli';

import { RootCommand } from "./commands/__root";

import { Command as IndexCommandImport } from "./commands/index";
import { Command as LayoutAuthCommandImport } from "./commands/_auth/route";
import { Command as LayoutAuthProtectedCommandImport } from "./commands/_auth/protected";
import { Command as AddSplatCommandImport } from "./commands/add/$";
import { Command as AuthCommandImport } from "./commands/auth";
import { Command as ListCommandImport } from "./commands/list/index";
import { Command as ListProjectIdCommandImport } from "./commands/list/$projectId";
import { Command as UseLinkCommandImport } from "./commands/useLink";

// Wire up parent relationships (like TanStack Router)
const IndexCommand = IndexCommandImport.update({
  id: "/",
  path: "/",
  getParentCommand: () => RootCommand,
});
const LayoutAuthCommand = LayoutAuthCommandImport.update({
  id: "/_auth",
  path: "/_auth",
  getParentCommand: () => RootCommand,
});
const LayoutAuthProtectedCommand = LayoutAuthProtectedCommandImport.update({
  id: "/_auth/protected",
  path: "/_auth/protected",
  getParentCommand: () => LayoutAuthCommand,
});
const AddSplatCommand = AddSplatCommandImport.update({
  id: "/add/$",
  path: "/add/$",
  getParentCommand: () => RootCommand,
});
const AuthCommand = AuthCommandImport.update({
  id: "/auth",
  path: "/auth",
  getParentCommand: () => RootCommand,
});
const ListCommand = ListCommandImport.update({
  id: "/list",
  path: "/list",
  getParentCommand: () => RootCommand,
});
const ListProjectIdCommand = ListProjectIdCommandImport.update({
  id: "/list/$projectId",
  path: "/list/$projectId",
  getParentCommand: () => ListCommand,
});
const UseLinkCommand = UseLinkCommandImport.update({
  id: "/useLink",
  path: "/useLink",
  getParentCommand: () => RootCommand,
});

export const commandsTree = {
  "/": IndexCommand,
  "/_auth": LayoutAuthCommand,
  "/_auth/protected": LayoutAuthProtectedCommand,
  "/add/$": AddSplatCommand,
  "/auth": AuthCommand,
  "/list": ListCommand,
  "/list/$projectId": ListProjectIdCommand,
  "/useLink": UseLinkCommand,
} as const;

// Register commands for type-safe commandInfo() helper
registerCommands(commandsTree);

export type CommandPath = keyof typeof commandsTree;

// Route table for argv parsing
export const routeTable: RouteTable = {
  staticRoutes: {
    "auth": "/auth",
    "list": "/list",
    "useLink": "/useLink",
    "protected": "/_auth/protected",
  },
  dynamicRoutes: [
    { segments: ["list", "$projectId"], path: "/list/$projectId", paramIndices: { projectId: 1 } },
  ],
  splatRoutes: [
    { parentSegments: ["add"], path: "/add/$" },
  ],
  availableCommands: ["protected", "add <items...>", "auth", "list", "list <projectId>", "useLink"],
};

/**
 * Parse process.argv into a ParsedRoute
 */
export const parseRoute = createParseRoute(commandsTree, routeTable);

// FileCommandsByPath for type-safe context inference
// This enables automatic context type inheritance from root command
declare module 'filerouter-cli' {
  interface FileCommandsByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      parentCommand: typeof RootCommand;
    };
    "/_auth": {
      id: "/_auth";
      path: "/_auth";
      fullPath: "/_auth";
      parentCommand: typeof RootCommand;
    };
    "/_auth/protected": {
      id: "/_auth/protected";
      path: "/protected";
      fullPath: "/_auth/protected";
      parentCommand: typeof LayoutAuthCommand;
    };
    "/add/$": {
      id: "/add/$";
      path: "/$";
      fullPath: "/add/$";
      parentCommand: typeof RootCommand;
    };
    "/auth": {
      id: "/auth";
      path: "/auth";
      fullPath: "/auth";
      parentCommand: typeof RootCommand;
    };
    "/list": {
      id: "/list";
      path: "/list";
      fullPath: "/list";
      parentCommand: typeof RootCommand;
    };
    "/list/$projectId": {
      id: "/list/$projectId";
      path: "/$projectId";
      fullPath: "/list/$projectId";
      parentCommand: typeof ListCommand;
    };
    "/useLink": {
      id: "/useLink";
      path: "/useLink";
      fullPath: "/useLink";
      parentCommand: typeof RootCommand;
    };
  }
}

// Type-safe runCommand support via declaration merging
// This extends the Register interface in filerouter-cli with actual command types

type RegisteredCommandPath = "/" | "/_auth" | "/_auth/protected" | "/add/$" | "/auth" | "/list" | "/list/$projectId" | "/useLink";

type CommandArgsMap = {
  "/": Record<string, unknown>;
  "/_auth": Record<string, unknown>;
  "/_auth/protected": Record<string, unknown>;
  "/add/$": Record<string, unknown>;
  "/auth": Record<string, unknown>;
  "/list": Record<string, unknown>;
  "/list/$projectId": Record<string, unknown>;
  "/useLink": Record<string, unknown>;
};

type CommandParamsMap = {
  "/": EmptyParams;
  "/_auth": EmptyParams;
  "/_auth/protected": EmptyParams;
  "/add/$": { _splat: string[] };
  "/auth": EmptyParams;
  "/list": EmptyParams;
  "/list/$projectId": { projectId: string };
  "/useLink": EmptyParams;
};

declare module 'filerouter-cli' {
  interface Register {
    commandPath: RegisteredCommandPath;
    commandArgs: CommandArgsMap;
    commandParams: CommandParamsMap;
  }
}