// AUTO-GENERATED by filerouter-cli - DO NOT EDIT
// Generated at: 2026-03-16T16:51:23.285Z

import { createParseRoute, registerCommands } from 'filerouter-cli';
import type { RouteTable, EmptyParams } from 'filerouter-cli';

import { Command as RootCommand } from "./commands/index";
import { Command as LayoutAuthCommand } from "./commands/_auth/route";
import { Command as LayoutAuthProtectedCommand } from "./commands/_auth/protected";
import { Command as AddSplatCommand } from "./commands/add/$";
import { Command as AuthCommand } from "./commands/auth";
import { Command as ListCommand } from "./commands/list/index";
import { Command as ListProjectIdCommand } from "./commands/list/$projectId";
import { Command as UseLinkCommand } from "./commands/useLink";

export const commandsTree = {
  "/": RootCommand,
  "/_auth": LayoutAuthCommand,
  "/_auth/protected": LayoutAuthProtectedCommand,
  "/add/$": AddSplatCommand,
  "/auth": AuthCommand,
  "/list": ListCommand,
  "/list/$projectId": ListProjectIdCommand,
  "/useLink": UseLinkCommand,
} as const;

// Register commands for type-safe commandInfo() helper
registerCommands(commandsTree, "my-cli");

export type CommandPath = keyof typeof commandsTree;

// Route table data for parseRoute
const routeTable: RouteTable = {
  staticRoutes: {
    "auth": "/auth",
    "list": "/list",
    "useLink": "/useLink",
    "protected": "/_auth/protected",
  },
  dynamicRoutes: [
    { segments: ["list", "$projectId"], path: "/list/$projectId", paramIndices: { projectId: 1 } },
  ],
  splatRoutes: [
    { parentSegments: ["add"], path: "/add/$" },
  ],
  availableCommands: ["protected", "add <items...>", "auth", "list", "list <projectId>", "useLink"],
};

/**
 * Parse process.argv into a ParsedRoute
 * @throws ParseError if the command is not found or arguments are invalid
 */
export const parseRoute = createParseRoute(commandsTree, routeTable);

// Type-safe runCommand support via declaration merging
// This extends the Register interface in filerouter-cli with actual command types

type RegisteredCommandPath = "/" | "/_auth" | "/_auth/protected" | "/add/$" | "/auth" | "/list" | "/list/$projectId" | "/useLink";

type CommandArgsMap = {
  "/": Record<string, unknown>;
  "/_auth": Record<string, unknown>;
  "/_auth/protected": Record<string, unknown>;
  "/add/$": Record<string, unknown>;
  "/auth": Record<string, unknown>;
  "/list": Record<string, unknown>;
  "/list/$projectId": Record<string, unknown>;
  "/useLink": Record<string, unknown>;
};

type CommandParamsMap = {
  "/": EmptyParams;
  "/_auth": EmptyParams;
  "/_auth/protected": EmptyParams;
  "/add/$": { _splat: string[] };
  "/auth": EmptyParams;
  "/list": EmptyParams;
  "/list/$projectId": { projectId: string };
  "/useLink": EmptyParams;
};

declare module 'filerouter-cli' {
  interface Register {
    commandPath: RegisteredCommandPath;
    commandArgs: CommandArgsMap;
    commandParams: CommandParamsMap;
  }
}