import { afterEach, beforeEach, describe, expect, it } from "bun:test";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "fs/promises";
import { tmpdir } from "os";
import { join } from "path";
import { generateCommandsTree } from "../../generator/codegen";
import type { GeneratorConfig, ScannedCommand } from "../../generator/types";

// Helper to create __root.ts file in a commands directory (following TanStack Router's naming convention)
async function createRootCommand(commandsDir: string): Promise<void> {
  await mkdir(commandsDir, { recursive: true });
  await writeFile(
    join(commandsDir, "__root.ts"),
    `import { createRootCommand } from "filerouter-cli";
export const RootCommand = createRootCommand()({ description: "Test CLI" });`,
  );
}

describe("generateCommandsTree", () => {
  let tempDir: string;
  let defaultConfig: GeneratorConfig;

  beforeEach(async () => {
    tempDir = await mkdtemp(join(tmpdir(), "filerouter-codegen-test-"));
    const commandsDir = join(tempDir, "commands");
    await createRootCommand(commandsDir);
    defaultConfig = {
      commandsDirectory: commandsDir,
      generatedFile: join(tempDir, "commandsTree.gen.ts"),
    };
  });

  afterEach(async () => {
    await rm(tempDir, { recursive: true, force: true });
  });

  describe("header generation", () => {
    it("includes auto-generated comment", () => {
      const code = generateCommandsTree([], defaultConfig);

      expect(code).toContain("AUTO-GENERATED by filerouter-cli");
      expect(code).toContain("DO NOT EDIT");
    });

    it("includes timestamp", () => {
      const code = generateCommandsTree([], defaultConfig);

      expect(code).toContain("Generated at:");
    });
  });

  describe("imports generation", () => {
    it("imports from filerouter-cli", () => {
      const code = generateCommandsTree([], defaultConfig);

      expect(code).toContain("import { createParseRoute, registerCommands } from 'filerouter-cli'");
      expect(code).toContain("import type { RouteTable, EmptyParams } from 'filerouter-cli'");
    });

    it("imports commands with correct variable names", () => {
      const commands: ScannedCommand[] = [
        {
          filePath: "auth.ts",
          routePath: "/auth",
          isLayout: false,
          isPathless: false,
          hasParams: false,
          isSplat: false,
          segments: ["auth"],
          paramNames: [],
        },
      ];

      const code = generateCommandsTree(commands, defaultConfig);

      // Import path includes the full temp directory path, just check the pattern
      expect(code).toContain('import { Command as AuthCommandImport } from "');
      expect(code).toContain('/auth"');
    });

    it("generates correct import path for nested commands", () => {
      const commands: ScannedCommand[] = [
        {
          filePath: "list/$projectId.ts",
          routePath: "/list/$projectId",
          isLayout: false,
          isPathless: false,
          hasParams: true,
          isSplat: false,
          segments: ["list", "$projectId"],
          paramNames: ["projectId"],
        },
      ];

      const code = generateCommandsTree(commands, defaultConfig);

      expect(code).toContain('import { Command as ListProjectIdCommandImport } from "');
      expect(code).toContain('/list/$projectId"');
    });

    it("handles layout imports", () => {
      const commands: ScannedCommand[] = [
        {
          filePath: "_auth/route.ts",
          routePath: "/_auth",
          isLayout: true,
          isPathless: true,
          hasParams: false,
          isSplat: false,
          segments: ["_auth"],
          paramNames: [],
        },
      ];

      const code = generateCommandsTree(commands, defaultConfig);

      expect(code).toContain('import { Command as LayoutAuthCommandImport } from "');
      expect(code).toContain('/_auth/route"');
    });

    it("handles splat imports", () => {
      const commands: ScannedCommand[] = [
        {
          filePath: "add/$.ts",
          routePath: "/add/$",
          isLayout: false,
          isPathless: false,
          hasParams: true,
          isSplat: true,
          segments: ["add", "$"],
          paramNames: ["_splat"],
        },
      ];

      const code = generateCommandsTree(commands, defaultConfig);

      expect(code).toContain('import { Command as AddSplatCommandImport } from "');
      expect(code).toContain('/add/$"');
    });
  });

  describe("commandsTree object", () => {
    it("generates commandsTree with routes", () => {
      const commands: ScannedCommand[] = [
        {
          filePath: "auth.ts",
          routePath: "/auth",
          isLayout: false,
          isPathless: false,
          hasParams: false,
          isSplat: false,
          segments: ["auth"],
          paramNames: [],
        },
        {
          filePath: "list.ts",
          routePath: "/list",
          isLayout: false,
          isPathless: false,
          hasParams: false,
          isSplat: false,
          segments: ["list"],
          paramNames: [],
        },
      ];

      const code = generateCommandsTree(commands, defaultConfig);

      expect(code).toContain("export const commandsTree = {");
      // Commands are referenced by their updated variable names
      expect(code).toContain('"/auth": AuthCommand,');
      expect(code).toContain('"/list": ListCommand,');
      expect(code).toContain("} as const;");
    });

    it("generates CommandPath type", () => {
      const code = generateCommandsTree([], defaultConfig);

      expect(code).toContain("export type CommandPath = keyof typeof commandsTree;");
    });
  });

  describe("routeTable export", () => {
    it("exports routeTable for use with router", () => {
      const code = generateCommandsTree([], defaultConfig);

      expect(code).toContain("export const routeTable: RouteTable = {");
    });
  });

  describe("routeTable generation", () => {
    it("generates routeTable constant with correct type", () => {
      const commands: ScannedCommand[] = [
        {
          filePath: "auth.ts",
          routePath: "/auth",
          isLayout: false,
          isPathless: false,
          hasParams: false,
          isSplat: false,
          segments: ["auth"],
          paramNames: [],
        },
      ];

      const code = generateCommandsTree(commands, defaultConfig);

      expect(code).toContain("const routeTable: RouteTable = {");
    });

    it("generates staticRoutes in routeTable", () => {
      const commands: ScannedCommand[] = [
        {
          filePath: "auth.ts",
          routePath: "/auth",
          isLayout: false,
          isPathless: false,
          hasParams: false,
          isSplat: false,
          segments: ["auth"],
          paramNames: [],
        },
        {
          filePath: "list.ts",
          routePath: "/list",
          isLayout: false,
          isPathless: false,
          hasParams: false,
          isSplat: false,
          segments: ["list"],
          paramNames: [],
        },
      ];

      const code = generateCommandsTree(commands, defaultConfig);

      expect(code).toContain("staticRoutes: {");
      expect(code).toContain('"auth": "/auth"');
      expect(code).toContain('"list": "/list"');
    });

    it("generates dynamicRoutes in routeTable", () => {
      const commands: ScannedCommand[] = [
        {
          filePath: "list/$projectId.ts",
          routePath: "/list/$projectId",
          isLayout: false,
          isPathless: false,
          hasParams: true,
          isSplat: false,
          segments: ["list", "$projectId"],
          paramNames: ["projectId"],
        },
      ];

      const code = generateCommandsTree(commands, defaultConfig);

      expect(code).toContain("dynamicRoutes: [");
      expect(code).toContain('segments: ["list", "$projectId"]');
      expect(code).toContain('path: "/list/$projectId"');
    });

    it("generates splatRoutes in routeTable", () => {
      const commands: ScannedCommand[] = [
        {
          filePath: "add/$.ts",
          routePath: "/add/$",
          isLayout: false,
          isPathless: false,
          hasParams: true,
          isSplat: true,
          segments: ["add", "$"],
          paramNames: ["_splat"],
        },
      ];

      const code = generateCommandsTree(commands, defaultConfig);

      expect(code).toContain("splatRoutes: [");
      expect(code).toContain('parentSegments: ["add"]');
      expect(code).toContain('path: "/add/$"');
    });

    it("generates availableCommands in routeTable", () => {
      const commands: ScannedCommand[] = [
        {
          filePath: "auth.ts",
          routePath: "/auth",
          isLayout: false,
          isPathless: false,
          hasParams: false,
          isSplat: false,
          segments: ["auth"],
          paramNames: [],
        },
      ];

      const code = generateCommandsTree(commands, defaultConfig);

      expect(code).toContain("availableCommands: [");
      expect(code).toContain('"auth"');
    });
  });

  describe("pathless layout handling", () => {
    it("pathless children are accessible without prefix", () => {
      const commands: ScannedCommand[] = [
        {
          filePath: "_auth/protected.ts",
          routePath: "/_auth/protected",
          isLayout: false,
          isPathless: true,
          hasParams: false,
          isSplat: false,
          segments: ["_auth", "protected"],
          paramNames: [],
        },
      ];

      const code = generateCommandsTree(commands, defaultConfig);

      // Should include in static routes map with CLI path (without _prefix)
      expect(code).toContain('"protected"');
    });
  });

  describe("registerCommands call", () => {
    it("calls registerCommands without cliName (cliName is determined at runtime)", () => {
      const code = generateCommandsTree([], defaultConfig);

      expect(code).toContain("registerCommands(commandsTree)");
      expect(code).not.toContain("registerCommands(commandsTree, ");
    });
  });
});

describe("generated code execution", () => {
  let tempDir: string;
  let commandsDir: string;

  beforeEach(async () => {
    tempDir = await mkdtemp(join(tmpdir(), "filerouter-codegen-exec-test-"));
    commandsDir = join(tempDir, "commands");
    await createRootCommand(commandsDir);
  });

  afterEach(async () => {
    await rm(tempDir, { recursive: true, force: true });
  });

  it("generates valid TypeScript code", async () => {
    const commands: ScannedCommand[] = [
      {
        filePath: "auth.ts",
        routePath: "/auth",
        isLayout: false,
        isPathless: false,
        hasParams: false,
        isSplat: false,
        segments: ["auth"],
        paramNames: [],
      },
    ];

    const code = generateCommandsTree(commands, {
      commandsDirectory: commandsDir,
      generatedFile: join(tempDir, "commandsTree.gen.ts"),
    });

    // Write the generated code
    await writeFile(join(tempDir, "commandsTree.gen.ts"), code);

    // Create mock command file
    await writeFile(
      join(commandsDir, "auth.ts"),
      `
      export const Command = {
        __path: "/auth",
        config: {
          description: "Test auth",
          handler: async () => "auth output",
        },
      };
    `,
    );

    // The code should be syntactically valid TypeScript
    // We can verify by attempting to parse it
    const content = await readFile(join(tempDir, "commandsTree.gen.ts"), "utf-8");
    expect(content).toContain("export const commandsTree");
    expect(content).toContain("export const routeTable");
  });

  it("generates code that handles multiple route types", async () => {
    const commands: ScannedCommand[] = [
      {
        filePath: "index.ts",
        routePath: "/",
        isLayout: false,
        isPathless: false,
        hasParams: false,
        isSplat: false,
        segments: [],
        paramNames: [],
      },
      {
        filePath: "auth.ts",
        routePath: "/auth",
        isLayout: false,
        isPathless: false,
        hasParams: false,
        isSplat: false,
        segments: ["auth"],
        paramNames: [],
      },
      {
        filePath: "list/$projectId.ts",
        routePath: "/list/$projectId",
        isLayout: false,
        isPathless: false,
        hasParams: true,
        isSplat: false,
        segments: ["list", "$projectId"],
        paramNames: ["projectId"],
      },
      {
        filePath: "add/$.ts",
        routePath: "/add/$",
        isLayout: false,
        isPathless: false,
        hasParams: true,
        isSplat: true,
        segments: ["add", "$"],
        paramNames: ["_splat"],
      },
      {
        filePath: "_auth/route.ts",
        routePath: "/_auth",
        isLayout: true,
        isPathless: true,
        hasParams: false,
        isSplat: false,
        segments: ["_auth"],
        paramNames: [],
      },
    ];

    const code = generateCommandsTree(commands, {
      commandsDirectory: commandsDir,
      generatedFile: join(tempDir, "commandsTree.gen.ts"),
    });

    // "/" is now IndexCommand (not RootCommand) to avoid conflict with RootCommand from __root.ts
    expect(code).toContain('"/": IndexCommand');
    expect(code).toContain('"/auth": AuthCommand');
    expect(code).toContain('"/list/$projectId": ListProjectIdCommand');
    expect(code).toContain('"/add/$": AddSplatCommand');
    expect(code).toContain('"/_auth": LayoutAuthCommand');

    // Verify route table includes all types
    expect(code).toContain("staticRoutes: {");
    expect(code).toContain("dynamicRoutes: [");
    expect(code).toContain("splatRoutes: [");
    expect(code).toContain("availableCommands: [");
  });
});
