import { describe, it, expect, beforeEach, afterEach } from "bun:test";
import { mkdtemp, rm, mkdir, writeFile, readFile } from "fs/promises";
import { join } from "path";
import { tmpdir } from "os";
import { generateCommandsTree } from "../../generator/codegen";
import type { ScannedCommand, GeneratorConfig } from "../../generator/types";

describe("generateCommandsTree", () => {
  const defaultConfig: GeneratorConfig = {
    commandsDirectory: "./commands",
    generatedFile: "./commandsTree.gen.ts",
    cliName: "test-cli",
  };

  describe("header generation", () => {
    it("includes auto-generated comment", () => {
      const code = generateCommandsTree([], defaultConfig);

      expect(code).toContain("AUTO-GENERATED by filerouter-cli");
      expect(code).toContain("DO NOT EDIT");
    });

    it("includes timestamp", () => {
      const code = generateCommandsTree([], defaultConfig);

      expect(code).toContain("Generated at:");
    });
  });

  describe("imports generation", () => {
    it("imports from filerouter-cli", () => {
      const code = generateCommandsTree([], defaultConfig);

      expect(code).toContain("import { ParseError, parseRawArgs, extractBooleanFlags } from 'filerouter-cli'");
      expect(code).toContain("import type { ParsedRoute, EmptyParams } from 'filerouter-cli'");
    });

    it("imports commands with correct variable names", () => {
      const commands: ScannedCommand[] = [
        {
          filePath: "auth.ts",
          routePath: "/auth",
          isLayout: false,
          isPathless: false,
          hasParams: false,
          isSplat: false,
          segments: ["auth"],
          paramNames: [],
        },
      ];

      const code = generateCommandsTree(commands, defaultConfig);

      expect(code).toContain('import { Command as AuthCommand } from "./commands/auth"');
    });

    it("generates correct import path for nested commands", () => {
      const commands: ScannedCommand[] = [
        {
          filePath: "list/$projectId.ts",
          routePath: "/list/$projectId",
          isLayout: false,
          isPathless: false,
          hasParams: true,
          isSplat: false,
          segments: ["list", "$projectId"],
          paramNames: ["projectId"],
        },
      ];

      const code = generateCommandsTree(commands, defaultConfig);

      expect(code).toContain('import { Command as ListProjectIdCommand } from "./commands/list/$projectId"');
    });

    it("handles layout imports", () => {
      const commands: ScannedCommand[] = [
        {
          filePath: "_auth/route.ts",
          routePath: "/_auth",
          isLayout: true,
          isPathless: true,
          hasParams: false,
          isSplat: false,
          segments: ["_auth"],
          paramNames: [],
        },
      ];

      const code = generateCommandsTree(commands, defaultConfig);

      expect(code).toContain('import { Command as LayoutAuthCommand } from "./commands/_auth/route"');
    });

    it("handles splat imports", () => {
      const commands: ScannedCommand[] = [
        {
          filePath: "add/$.ts",
          routePath: "/add/$",
          isLayout: false,
          isPathless: false,
          hasParams: true,
          isSplat: true,
          segments: ["add", "$"],
          paramNames: ["_splat"],
        },
      ];

      const code = generateCommandsTree(commands, defaultConfig);

      expect(code).toContain('import { Command as AddSplatCommand } from "./commands/add/$"');
    });
  });

  describe("commandsTree object", () => {
    it("generates commandsTree with routes", () => {
      const commands: ScannedCommand[] = [
        {
          filePath: "auth.ts",
          routePath: "/auth",
          isLayout: false,
          isPathless: false,
          hasParams: false,
          isSplat: false,
          segments: ["auth"],
          paramNames: [],
        },
        {
          filePath: "list.ts",
          routePath: "/list",
          isLayout: false,
          isPathless: false,
          hasParams: false,
          isSplat: false,
          segments: ["list"],
          paramNames: [],
        },
      ];

      const code = generateCommandsTree(commands, defaultConfig);

      expect(code).toContain("export const commandsTree = {");
      expect(code).toContain('"/auth": AuthCommand,');
      expect(code).toContain('"/list": ListCommand,');
      expect(code).toContain("} as const;");
    });

    it("generates CommandPath type", () => {
      const code = generateCommandsTree([], defaultConfig);

      expect(code).toContain("export type CommandPath = keyof typeof commandsTree;");
    });
  });

  describe("parseRoute function", () => {
    it("generates parseRoute function", () => {
      const code = generateCommandsTree([], defaultConfig);

      expect(code).toContain("export function parseRoute(argv: string[]): ParsedRoute {");
    });

    it("includes two-pass parsing logic", () => {
      const commands: ScannedCommand[] = [
        {
          filePath: "auth.ts",
          routePath: "/auth",
          isLayout: false,
          isPathless: false,
          hasParams: false,
          isSplat: false,
          segments: ["auth"],
          paramNames: [],
        },
      ];

      const code = generateCommandsTree(commands, defaultConfig);

      // First pass: extract positional args
      expect(code).toContain("First pass");
      expect(code).toContain("positional");

      // Second pass: re-parse with schema knowledge
      expect(code).toContain("Second pass");
      expect(code).toContain("extractBooleanFlags");
    });

    it("includes boolean flag awareness", () => {
      const commands: ScannedCommand[] = [
        {
          filePath: "add.ts",
          routePath: "/add",
          isLayout: false,
          isPathless: false,
          hasParams: false,
          isSplat: false,
          segments: ["add"],
          paramNames: [],
        },
      ];

      const code = generateCommandsTree(commands, defaultConfig);

      expect(code).toContain("booleanFlags");
      expect(code).toContain("parseRawArgs(args, { booleanFlags })");
    });
  });

  describe("matchRoute function", () => {
    it("generates matchRoute function", () => {
      const commands: ScannedCommand[] = [
        {
          filePath: "auth.ts",
          routePath: "/auth",
          isLayout: false,
          isPathless: false,
          hasParams: false,
          isSplat: false,
          segments: ["auth"],
          paramNames: [],
        },
      ];

      const code = generateCommandsTree(commands, defaultConfig);

      expect(code).toContain("function matchRoute(positional: string[]): RouteMatch {");
    });

    it("handles static routes", () => {
      const commands: ScannedCommand[] = [
        {
          filePath: "auth.ts",
          routePath: "/auth",
          isLayout: false,
          isPathless: false,
          hasParams: false,
          isSplat: false,
          segments: ["auth"],
          paramNames: [],
        },
        {
          filePath: "list.ts",
          routePath: "/list",
          isLayout: false,
          isPathless: false,
          hasParams: false,
          isSplat: false,
          segments: ["list"],
          paramNames: [],
        },
      ];

      const code = generateCommandsTree(commands, defaultConfig);

      expect(code).toContain("staticRoutes");
      expect(code).toContain('"auth": "/auth"');
      expect(code).toContain('"list": "/list"');
    });

    it("handles dynamic routes", () => {
      const commands: ScannedCommand[] = [
        {
          filePath: "list/$projectId.ts",
          routePath: "/list/$projectId",
          isLayout: false,
          isPathless: false,
          hasParams: true,
          isSplat: false,
          segments: ["list", "$projectId"],
          paramNames: ["projectId"],
        },
      ];

      const code = generateCommandsTree(commands, defaultConfig);

      expect(code).toContain("dynamicRoutes");
      expect(code).toContain('segments: ["list", "$projectId"]');
      expect(code).toContain('path: "/list/$projectId"');
    });

    it("handles splat routes (lowest priority)", () => {
      const commands: ScannedCommand[] = [
        {
          filePath: "add/$.ts",
          routePath: "/add/$",
          isLayout: false,
          isPathless: false,
          hasParams: true,
          isSplat: true,
          segments: ["add", "$"],
          paramNames: ["_splat"],
        },
      ];

      const code = generateCommandsTree(commands, defaultConfig);

      expect(code).toContain("splatRoutes");
      expect(code).toContain('parentSegments: ["add"]');
      expect(code).toContain('path: "/add/$"');
      expect(code).toContain("_splat");
    });

    it("handles root command", () => {
      const commands: ScannedCommand[] = [
        {
          filePath: "index.ts",
          routePath: "/",
          isLayout: false,
          isPathless: false,
          hasParams: false,
          isSplat: false,
          segments: [],
          paramNames: [],
        },
      ];

      const code = generateCommandsTree(commands, defaultConfig);

      expect(code).toContain("if (numPositional === 0)");
      expect(code).toContain("return { path: '/', params: {} }");
    });

    it("includes case-insensitive matching", () => {
      const commands: ScannedCommand[] = [
        {
          filePath: "auth.ts",
          routePath: "/auth",
          isLayout: false,
          isPathless: false,
          hasParams: false,
          isSplat: false,
          segments: ["auth"],
          paramNames: [],
        },
      ];

      const code = generateCommandsTree(commands, defaultConfig);

      expect(code).toContain(".toLowerCase()");
    });

    it("throws ParseError for unknown command", () => {
      const commands: ScannedCommand[] = [
        {
          filePath: "auth.ts",
          routePath: "/auth",
          isLayout: false,
          isPathless: false,
          hasParams: false,
          isSplat: false,
          segments: ["auth"],
          paramNames: [],
        },
      ];

      const code = generateCommandsTree(commands, defaultConfig);

      expect(code).toContain("throw new ParseError");
      expect(code).toContain("Unknown command");
      expect(code).toContain("UNKNOWN_COMMAND");
    });
  });

  describe("commandInfo function", () => {
    it("generates commandInfo function", () => {
      const code = generateCommandsTree([], defaultConfig);

      expect(code).toContain("export function commandInfo(path: CommandPath)");
    });

    it("returns description and usage", () => {
      const code = generateCommandsTree([], defaultConfig);

      expect(code).toContain("description: cmd.config.description");
      expect(code).toContain("usage: () => {");
    });

    it("uses configured cliName", () => {
      const config = { ...defaultConfig, cliName: "my-awesome-cli" };
      const code = generateCommandsTree([], config);

      expect(code).toContain('"my-awesome-cli"');
    });
  });

  describe("greedy matching", () => {
    it("implements longest match first strategy", () => {
      const commands: ScannedCommand[] = [
        {
          filePath: "auth.ts",
          routePath: "/auth",
          isLayout: false,
          isPathless: false,
          hasParams: false,
          isSplat: false,
          segments: ["auth"],
          paramNames: [],
        },
      ];

      const code = generateCommandsTree(commands, defaultConfig);

      // Should try longest prefix first
      expect(code).toContain("for (let len = numPositional; len >= 1; len--)");
    });
  });

  describe("pathless layout handling", () => {
    it("pathless children are accessible without prefix", () => {
      const commands: ScannedCommand[] = [
        {
          filePath: "_auth/protected.ts",
          routePath: "/_auth/protected",
          isLayout: false,
          isPathless: true,
          hasParams: false,
          isSplat: false,
          segments: ["_auth", "protected"],
          paramNames: [],
        },
      ];

      const code = generateCommandsTree(commands, defaultConfig);

      // Should include in static routes map with CLI path (without _prefix)
      expect(code).toContain('"protected"');
    });
  });
});

describe("generated code execution", () => {
  let tempDir: string;

  beforeEach(async () => {
    tempDir = await mkdtemp(join(tmpdir(), "filerouter-codegen-test-"));
  });

  afterEach(async () => {
    await rm(tempDir, { recursive: true, force: true });
  });

  it("generates valid TypeScript code", async () => {
    const commands: ScannedCommand[] = [
      {
        filePath: "auth.ts",
        routePath: "/auth",
        isLayout: false,
        isPathless: false,
        hasParams: false,
        isSplat: false,
        segments: ["auth"],
        paramNames: [],
      },
    ];

    const code = generateCommandsTree(commands, {
      commandsDirectory: "./commands",
      generatedFile: join(tempDir, "commandsTree.gen.ts"),
      cliName: "test-cli",
    });

    // Write the generated code
    await writeFile(join(tempDir, "commandsTree.gen.ts"), code);

    // Create mock command file
    await mkdir(join(tempDir, "commands"), { recursive: true });
    await writeFile(
      join(tempDir, "commands/auth.ts"),
      `
      export const Command = {
        __path: "/auth",
        config: {
          description: "Test auth",
          handler: async () => "auth output",
        },
      };
    `
    );

    // The code should be syntactically valid TypeScript
    // We can verify by attempting to parse it
    const content = await readFile(join(tempDir, "commandsTree.gen.ts"), "utf-8");
    expect(content).toContain("export const commandsTree");
    expect(content).toContain("export function parseRoute");
  });

  it("generates code that handles multiple route types", async () => {
    const commands: ScannedCommand[] = [
      {
        filePath: "index.ts",
        routePath: "/",
        isLayout: false,
        isPathless: false,
        hasParams: false,
        isSplat: false,
        segments: [],
        paramNames: [],
      },
      {
        filePath: "auth.ts",
        routePath: "/auth",
        isLayout: false,
        isPathless: false,
        hasParams: false,
        isSplat: false,
        segments: ["auth"],
        paramNames: [],
      },
      {
        filePath: "list/$projectId.ts",
        routePath: "/list/$projectId",
        isLayout: false,
        isPathless: false,
        hasParams: true,
        isSplat: false,
        segments: ["list", "$projectId"],
        paramNames: ["projectId"],
      },
      {
        filePath: "add/$.ts",
        routePath: "/add/$",
        isLayout: false,
        isPathless: false,
        hasParams: true,
        isSplat: true,
        segments: ["add", "$"],
        paramNames: ["_splat"],
      },
      {
        filePath: "_auth/route.ts",
        routePath: "/_auth",
        isLayout: true,
        isPathless: true,
        hasParams: false,
        isSplat: false,
        segments: ["_auth"],
        paramNames: [],
      },
    ];

    const code = generateCommandsTree(commands, {
      commandsDirectory: "./commands",
      generatedFile: join(tempDir, "commandsTree.gen.ts"),
      cliName: "test-cli",
    });

    // Verify all route types are present
    expect(code).toContain('"/": RootCommand');
    expect(code).toContain('"/auth": AuthCommand');
    expect(code).toContain('"/list/$projectId": ListProjectIdCommand');
    expect(code).toContain('"/add/$": AddSplatCommand');
    expect(code).toContain('"/_auth": LayoutAuthCommand');

    // Verify matching logic includes all types
    expect(code).toContain("staticRoutes");
    expect(code).toContain("dynamicRoutes");
    expect(code).toContain("splatRoutes");
  });
});
