import * as fs from "fs";
import * as path from "path";
import { extractRouteParams } from "../parseRoute";
import { routePathToCliCommand, routePathToVarName } from "./scanner";
import type { GeneratorConfig, ScannedCommand } from "./types";

/**
 * Check if __root.ts exists in the commands directory
 * (Following TanStack Router's naming convention)
 */
function checkRootCommandExists(config: GeneratorConfig): boolean {
  const rootPath = path.join(config.commandsDirectory, "__root.ts");
  const rootTsxPath = path.join(config.commandsDirectory, "__root.tsx");
  return fs.existsSync(rootPath) || fs.existsSync(rootTsxPath);
}

/**
 * Get the file extension for root command (ts or tsx)
 */
function _getRootCommandExtension(config: GeneratorConfig): string {
  const rootTsxPath = path.join(config.commandsDirectory, "__root.tsx");
  if (fs.existsSync(rootTsxPath)) {
    return "tsx";
  }
  return "ts";
}

/**
 * Determine the parent command for a given route path
 *
 * For nested routes, find the nearest parent:
 * - "/list/$projectId" -> parent is "/list" if it exists, otherwise RootCommand
 * - "/list" -> parent is RootCommand (not "/" - top-level routes always parent to RootCommand)
 * - "/_auth/protected" -> parent is "/_auth" (layout)
 * - "/" -> parent is RootCommand
 *
 * Note: "/" (IndexCommand) is NOT considered a parent for other top-level routes.
 * All top-level routes (/auth, /list, /_auth, etc.) parent directly to RootCommand.
 */
function getParentCommand(
  routePath: string,
  commands: ScannedCommand[],
): { varName: string; isRoot: boolean } {
  if (routePath === "/") {
    return { varName: "RootCommand", isRoot: true };
  }

  const segments = routePath.split("/").filter(Boolean);

  // Try to find parent by removing last segment
  while (segments.length > 0) {
    segments.pop();
    const parentPath = segments.length === 0 ? "/" : `/${segments.join("/")}`;

    // "/" is not a parent for other routes - only RootCommand (from root.ts) is
    // This ensures context flows from RootCommand, not from IndexCommand
    if (parentPath === "/") {
      return { varName: "RootCommand", isRoot: true };
    }

    // Check if this parent exists in commands
    const parentCmd = commands.find((c) => c.routePath === parentPath);
    if (parentCmd) {
      return { varName: `${routePathToVarName(parentPath)}Command`, isRoot: false };
    }
  }

  // Default to RootCommand
  return { varName: "RootCommand", isRoot: true };
}

/**
 * Generate the commandsTree.gen.ts file content
 */
export function generateCommandsTree(commands: ScannedCommand[], config: GeneratorConfig): string {
  // Check for __root.ts - it's required (following TanStack Router's naming convention)
  if (!checkRootCommandExists(config)) {
    throw new Error(
      `__root.ts is required in the commands directory (${config.commandsDirectory}).\n` +
        `Create a __root.ts file with:\n\n` +
        `import { createRootCommand } from "filerouter-cli";\n\n` +
        `export const RootCommand = createRootCommand()({ description: "My CLI" });\n`,
    );
  }

  const lines: string[] = [];

  // Header
  lines.push("// AUTO-GENERATED by filerouter-cli - DO NOT EDIT");
  lines.push(`// Generated at: ${new Date().toISOString()}`);
  lines.push("");

  // Imports from filerouter-cli
  lines.push('import type { EmptyParams, RouteTable } from "filerouter-cli";');
  lines.push('import { createParseRoute, registerCommands } from "filerouter-cli";');
  lines.push("");

  // Import root command first (defines context type)
  // Normalize commandsDirectory - remove leading "./" if present, then add it back
  const normalizedCmdDir = config.commandsDirectory.replace(/^\.\//, "");
  const rootImportPath = `./${normalizedCmdDir}/__root`;
  lines.push(`import { RootCommand } from "${rootImportPath}";`);
  lines.push("");

  // Command imports (skip root "/" as it's separate)
  for (const cmd of commands) {
    const varName = routePathToVarName(cmd.routePath);
    const importPath = getImportPath(cmd.filePath, config);
    lines.push(`import { Command as ${varName}CommandImport } from "${importPath}";`);
  }
  lines.push("");

  // Generate .update() calls to wire up parent relationships
  lines.push("// Wire up parent relationships (like TanStack Router)");
  for (const cmd of commands) {
    const varName = routePathToVarName(cmd.routePath);
    const parent = getParentCommand(cmd.routePath, commands);

    // Use RootCommand directly for "/" path's parent reference
    const parentRef = parent.isRoot ? "RootCommand" : parent.varName;

    lines.push(`const ${varName}Command = ${varName}CommandImport.update({`);
    lines.push(`  id: "${cmd.routePath}",`);
    lines.push(`  path: "${cmd.routePath}",`);
    lines.push(`  getParentCommand: () => ${parentRef},`);
    lines.push(`});`);
  }
  lines.push("");

  // Commands tree object
  lines.push("export const commandsTree = {");
  for (const cmd of commands) {
    const varName = routePathToVarName(cmd.routePath);
    lines.push(`  "${cmd.routePath}": ${varName}Command,`);
  }
  lines.push("} as const;");
  lines.push("");

  // Register commands for commandInfo() to work
  lines.push(`// Register commands for type-safe commandInfo() helper`);
  lines.push(`registerCommands(commandsTree);`);
  lines.push("");

  // Type definitions
  lines.push("export type CommandPath = keyof typeof commandsTree;");
  lines.push("");

  // Generate route table data and parseRoute
  lines.push(generateRouteTable(commands));

  // Generate FileCommandsByPath declaration for type-safe context
  lines.push(generateFileCommandsByPath(commands));

  // Generate Register declaration for type-safe runCommand
  lines.push(generateRegisterDeclaration(commands));

  return lines.join("\n");
}

/**
 * Get the import path for a command file
 */
function getImportPath(filePath: string, config: GeneratorConfig): string {
  // Remove extension
  const withoutExt = filePath.replace(/\.(ts|tsx|js|jsx)$/, "");

  // Make relative to the generated file location
  const _genDir = path.dirname(config.generatedFile);
  const cmdDir = config.commandsDirectory;

  // Build the relative path
  const relativePath = path.join(cmdDir, withoutExt);

  // Ensure it starts with ./
  if (!relativePath.startsWith(".")) {
    return `./${relativePath}`;
  }
  return relativePath;
}

/**
 * Generate the route table data and parseRoute function
 *
 * The route table contains all the data needed for route matching,
 * while the actual matching logic lives in the library (createParseRoute).
 */
function generateRouteTable(commands: ScannedCommand[]): string {
  const lines: string[] = [];

  // Separate routes by type
  const staticRoutes = commands.filter(
    (c) => !c.hasParams && !c.isPathless && !c.isLayout && !c.isSplat,
  );
  const dynamicRoutes = commands.filter((c) => c.hasParams && !c.isLayout && !c.isSplat);
  const splatRoutes = commands.filter((c) => c.isSplat);

  // Children of pathless layouts are accessible
  const pathlessChildren = commands.filter(
    (c) => c.isPathless && !c.isLayout && !c.hasParams && !c.isSplat,
  );
  const pathlessChildrenDynamic = commands.filter(
    (c) => c.isPathless && !c.isLayout && c.hasParams && !c.isSplat,
  );

  const allStaticRoutes = [...staticRoutes, ...pathlessChildren];
  const allDynamicRoutes = [...dynamicRoutes, ...pathlessChildrenDynamic];

  // Generate available commands list for error messages
  const availableCommands = commands
    .filter((c) => !c.isLayout)
    .map((c) => routePathToCliCommand(c.routePath))
    .filter(Boolean);

  lines.push("// Route table for argv parsing");
  lines.push("export const routeTable: RouteTable = {");

  // Static routes
  lines.push("  staticRoutes: {");
  for (const route of allStaticRoutes) {
    if (route.routePath === "/") continue;
    const cliCmd = routePathToCliCommand(route.routePath);
    if (cliCmd) {
      lines.push(`    "${cliCmd.replace(/ /g, "/")}": "${route.routePath}",`);
    }
  }
  lines.push("  },");

  // Dynamic routes
  lines.push("  dynamicRoutes: [");
  for (const route of allDynamicRoutes) {
    const segments = route.segments.filter((s) => !s.startsWith("_"));
    const paramIndices: string[] = [];

    for (let i = 0; i < segments.length; i++) {
      const seg = segments[i];
      if (seg.startsWith("$")) {
        paramIndices.push(`${seg.slice(1)}: ${i}`);
      }
    }

    lines.push(
      `    { segments: [${segments.map((s) => `"${s}"`).join(", ")}], path: "${route.routePath}", paramIndices: { ${paramIndices.join(", ")} } },`,
    );
  }
  lines.push("  ],");

  // Splat routes
  lines.push("  splatRoutes: [");
  for (const route of splatRoutes) {
    const parentSegments = route.segments.filter((s) => s !== "$" && !s.startsWith("_"));
    lines.push(
      `    { parentSegments: [${parentSegments.map((s) => `"${s}"`).join(", ")}], path: "${route.routePath}" },`,
    );
  }
  lines.push("  ],");

  // Available commands
  lines.push(`  availableCommands: [${availableCommands.map((c) => `"${c}"`).join(", ")}],`);

  lines.push("};");
  lines.push("");

  // Generate parseRoute using library function
  lines.push("/**");
  lines.push(" * Parse process.argv into a ParsedRoute");
  lines.push(" */");
  lines.push("export const parseRoute = createParseRoute(commandsTree, routeTable);");

  return lines.join("\n");
}

/**
 * Generate FileCommandsByPath declaration for type-safe context inference
 *
 * This maps each command path to its parent command type, enabling automatic
 * context type inference in createFileCommand without manual type annotations.
 */
function generateFileCommandsByPath(commands: ScannedCommand[]): string {
  const lines: string[] = [];

  lines.push("");
  lines.push("// FileCommandsByPath for type-safe context inference");
  lines.push("// This enables automatic context type inheritance from root command");
  lines.push('declare module "filerouter-cli" {');
  lines.push("  interface FileCommandsByPath {");

  for (const cmd of commands) {
    const parent = getParentCommand(cmd.routePath, commands);
    const _varName = routePathToVarName(cmd.routePath);

    // Calculate path segment (last part of the route)
    const segments = cmd.routePath.split("/").filter(Boolean);
    const pathSegment = segments.length > 0 ? `/${segments[segments.length - 1]}` : "/";

    lines.push(`    "${cmd.routePath}": {`);
    lines.push(`      id: "${cmd.routePath}";`);
    lines.push(`      path: "${pathSegment}";`);
    lines.push(`      fullPath: "${cmd.routePath}";`);
    lines.push(`      parentCommand: typeof ${parent.varName};`);
    lines.push(`    };`);
  }

  lines.push("  }");
  lines.push("}");

  return lines.join("\n");
}

/**
 * Generate the Register declaration for type-safe runCommand
 *
 * This uses TypeScript declaration merging to extend the Register interface
 * in filerouter-cli with the actual command types from this project.
 *
 * Note: We use a separate type alias for CommandPath in the Register to avoid
 * circular references when commands use runCommand().
 */
function generateRegisterDeclaration(commands: ScannedCommand[]): string {
  const lines: string[] = [];

  lines.push("");
  lines.push("// Type-safe runCommand support via declaration merging");
  lines.push("// This extends the Register interface in filerouter-cli with actual command types");
  lines.push("");

  // Generate a path literal union directly (not referencing CommandPath which can cause cycles)
  const pathUnion = commands.map((cmd) => `"${cmd.routePath}"`).join(" | ");
  lines.push(`type RegisteredCommandPath = ${pathUnion};`);
  lines.push("");

  // Generate CommandArgsMap - for now, use Record<string, unknown> as a simple fallback
  // Full type inference from validateArgs schemas would require more complex codegen
  // that reads and parses the actual schema definitions
  lines.push("type CommandArgsMap = {");
  for (const cmd of commands) {
    // For simplicity, we use Record<string, unknown> for all args
    // This still provides path validation while avoiding circular reference issues
    // Users get full type safety within their handlers from createFileCommand's inference
    lines.push(`  "${cmd.routePath}": Record<string, unknown>;`);
  }
  lines.push("};");
  lines.push("");

  // Generate CommandParamsMap - derive params type from route path
  // Use EmptyParams type from filerouter-cli for commands without params
  lines.push("type CommandParamsMap = {");
  for (const cmd of commands) {
    const params = extractRouteParams(cmd.routePath);
    if (params.length === 0) {
      // Import EmptyParams will be handled by adding to imports
      lines.push(`  "${cmd.routePath}": EmptyParams;`);
    } else {
      const paramTypes = params.map((p) => {
        if (p === "_splat") {
          return `_splat: string[]`;
        }
        return `${p}: string`;
      });
      lines.push(`  "${cmd.routePath}": { ${paramTypes.join("; ")} };`);
    }
  }
  lines.push("};");
  lines.push("");

  // Generate the declaration merging
  lines.push('declare module "filerouter-cli" {');
  lines.push("  interface Register {");
  lines.push("    commandPath: RegisteredCommandPath;");
  lines.push("    commandArgs: CommandArgsMap;");
  lines.push("    commandParams: CommandParamsMap;");
  lines.push("  }");
  lines.push("}");

  return lines.join("\n");
}
