import { ParseError } from "./errors";
import { extractBooleanFlags, parseRawArgs } from "./parser";
import type { FileCommand, ParsedRoute } from "./types";

/**
 * Extract param names from a route path.
 *
 * @example
 * extractRouteParams("/list/$projectId") // ["projectId"]
 * extractRouteParams("/add/$")           // ["_splat"]
 * extractRouteParams("/static")          // []
 */
export function extractRouteParams(routePath: string): string[] {
  const params: string[] = [];
  for (const segment of routePath.split("/")) {
    if (segment.startsWith("$")) {
      params.push(segment.slice(1) || "_splat");
    }
  }
  return params;
}

/**
 * Route table containing all route data for matching
 * This is generated by codegen and passed to createParseRoute
 */
export interface RouteTable {
  /** Static routes: CLI path (e.g., "auth") -> route path (e.g., "/auth") */
  staticRoutes: Record<string, string>;
  /** Dynamic routes with param placeholders */
  dynamicRoutes: Array<{
    segments: string[];
    path: string;
    paramIndices: Record<string, number>;
  }>;
  /** Splat routes ($.ts files) */
  splatRoutes: Array<{
    parentSegments: string[];
    path: string;
  }>;
  /** Available command names for error messages */
  availableCommands: string[];
}

interface RouteMatch {
  path: string;
  params: Record<string, string | string[]>;
}

/**
 * Match positional arguments to a route
 *
 * Uses greedy matching: tries longest match first, then shorter prefixes.
 * This allows commands like `add -D typescript` where `add` is the command
 * and `typescript` is an extra positional arg (not part of the route).
 *
 * Splat routes ($.ts) match LAST and capture remaining positional args.
 */
function matchRoute(positional: string[], routeTable: RouteTable): RouteMatch {
  const { staticRoutes, dynamicRoutes, splatRoutes, availableCommands } = routeTable;
  const numPositional = positional.length;

  // Root command
  if (numPositional === 0) {
    return { path: "/", params: {} };
  }

  // Try matching from longest prefix to shortest
  for (let len = numPositional; len >= 1; len--) {
    const prefix = positional.slice(0, len);
    const normalizedPrefix = `/${prefix.join("/").toLowerCase()}`;

    // Check static routes
    for (const [cliPath, routePath] of Object.entries(staticRoutes)) {
      if (normalizedPrefix === `/${cliPath.toLowerCase()}`) {
        return { path: routePath, params: {} };
      }
    }

    // Check dynamic routes
    for (const route of dynamicRoutes) {
      if (route.segments.length !== len) continue;

      let match = true;
      const params: Record<string, string> = {};

      for (let i = 0; i < len; i++) {
        const seg = route.segments[i];
        if (seg.startsWith("$")) {
          // Dynamic segment - capture param
          params[seg.slice(1)] = prefix[i];
        } else if (seg.toLowerCase() !== prefix[i].toLowerCase()) {
          // Static segment - must match
          match = false;
          break;
        }
      }

      if (match) {
        return { path: route.path, params };
      }
    }
  }

  // Splat routes (lowest priority) - capture remaining args
  // Sort by specificity (longest parent first)
  const sortedSplatRoutes = [...splatRoutes].sort(
    (a, b) => b.parentSegments.length - a.parentSegments.length,
  );

  for (const splat of sortedSplatRoutes) {
    const parentLen = splat.parentSegments.length;

    // Check if we have enough positional args for the parent
    if (numPositional >= parentLen) {
      let parentMatch = true;

      // Check parent segments match
      for (let i = 0; i < parentLen; i++) {
        if (splat.parentSegments[i].toLowerCase() !== positional[i].toLowerCase()) {
          parentMatch = false;
          break;
        }
      }

      if (parentMatch) {
        // Capture remaining positional args as _splat
        const splatArgs = positional.slice(parentLen);
        return { path: splat.path, params: { _splat: splatArgs } };
      }
    }
  }

  // No match found
  throw new ParseError(
    `Unknown command: ${positional.join(" ")}`,
    `Available commands:\n${availableCommands.map((c) => `  ${c}`).join("\n")}`,
    "UNKNOWN_COMMAND",
  );
}

/**
 * Create a parseRoute function for a specific commands tree and route table
 *
 * @example
 * ```ts
 * // In generated commandsTree.gen.ts
 * import { createParseRoute } from 'filerouter-cli';
 *
 * const routeTable = { ... };  // Generated route data
 * export const parseRoute = createParseRoute(commandsTree, routeTable);
 *
 * // In main.ts
 * const route = parseRoute(process.argv);
 * await router.run(route);
 * ```
 */
export function createParseRoute(
  commandsTree: Record<string, FileCommand<any, any, any, any>>,
  routeTable: RouteTable,
): (argv: string[]) => ParsedRoute {
  return (argv: string[]): ParsedRoute => {
    // Remove 'bun'/'node' and script path
    const args = argv.slice(2);

    // First pass: Extract positional args to identify the command
    // Skip anything that looks like a flag
    const positional: string[] = [];
    for (const arg of args) {
      if (arg === "--") break;
      if (!arg.startsWith("-")) {
        positional.push(arg);
      }
    }

    // Match route to find the command
    const routeInfo = matchRoute(positional, routeTable);

    // Second pass: Re-parse args with schema knowledge
    const command = commandsTree[routeInfo.path];
    const schema = command?.config?.validateArgs;
    const aliases = command?.config?.aliases;
    const booleanFlags = extractBooleanFlags(schema, aliases);

    // Parse with boolean flag awareness
    const { flags } = parseRawArgs(args, { booleanFlags });

    return {
      path: routeInfo.path,
      params: routeInfo.params,
      args: flags,
      rawArgs: args,
    };
  };
}
